// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kfytudtgcdutwqxdkzpf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtmeXR1ZHRnY2R1dHdxeGRrenBmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg0NjY5MjUsImV4cCI6MjA3NDA0MjkyNX0.iVDWd_dsZ0avyjzOjPIfo1z3eKafnbUNX2dv5lG1zoI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});